# Generated by Django 4.1.4 on 2023-04-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muscleGroup', models.CharField(choices=[('Chest', 'Chest'), ('Biceps', 'Biceps'), ('Tricep', 'Tricep'), ('Legs', 'Legs'), ('Abs', 'Abs'), ('Back', 'Back'), ('Shoulder', 'Shoulder')], max_length=255)),
                ('nameOfExercise', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=255)),
                ('firstMuscleGroup', models.CharField(max_length=255)),
                ('secondMuscleGroup', models.CharField(blank=True, max_length=255, null=True)),
                ('workoutImage', models.ImageField(null=True, upload_to='static/images/abs')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MealType', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('ingredients', models.CharField(max_length=1000)),
                ('steps', models.CharField(max_length=2000)),
                ('nutrition', models.CharField(max_length=255, null=True)),
                ('foodImage', models.ImageField(null=True, upload_to='static/images/food')),
            ],
        ),
    ]
