# Generated by Django 4.1.4 on 2023-04-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_userinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/pictures'),
        ),
    ]
